version: '3.3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    environment:
      - CHOKDIR_USERPOOLING=true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    container_name: client_c
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
