version: '3.3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    environment:
      - CHOKDIR_USERPOOLING=true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client_c
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
